# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "vmd"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a9390fca-9ec2-4248-b003-a6ce47ad4fab";
    fsType = "ext4";
  };

  boot.initrd.luks.devices = {
    "luks-aa168861-6ecf-4fcc-8a0d-6e1555892747".device = "/dev/disk/by-uuid/aa168861-6ecf-4fcc-8a0d-6e1555892747";
    "luks-92db61c9-eb4c-4cde-bd08-7042ff8db4ad".device = "/dev/disk/by-uuid/92db61c9-eb4c-4cde-bd08-7042ff8db4ad";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/90C1-FFCD";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-92db61c9-eb4c-4cde-bd08-7042ff8db4ad"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
